# SPDX-FileCopyrightText: © 2021-2022 MONAI Consortium
# SPDX-License-Identifier: Apache License 2.0

assembly-versioning-scheme: MajorMinorPatchTag
mode: ContinuousDelivery
branches:
  main:
    tag: ''
  release:
    tag: rc
  develop:
    tag: beta
  feature:
    tag: alpha.{BranchName}
  pull-request:
    tag: pr

ignore:
  sha: []
merge-message-formats: {}
