codecov:
  require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

fixes:
  - "/home/runner/work/Informatics-Gateway/Informatics-Gateway/src/::src/"
