# SPDX-FileCopyrightText: © 2021-2022 MONAI Consortium
# SPDX-License-Identifier: Apache License 2.0

apiRules:
- exclude:
    hasAttribute:
      uid: Newtonsoft.Json.JsonIgnoreAttribute
- exclude:
    uidRegex: ^FellowOakDicom\.Serialization\..*$
    type: Type
- exclude:
    # inherited Object methods
    uidRegex: ^System\.Object\..*$
    type: Method
