# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Cleanup Pre-release Packages

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/delete-package-versions@v4
      name: Monai.Deploy.InformaticsGateway.Api
      with: 
        package-name: 'Monai.Deploy.InformaticsGateway.Api'
        package-type: nuget
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - uses: actions/delete-package-versions@v4
      name: monai-deploy-informatics-gateway
      with: 
        package-name: 'monai-deploy-informatics-gateway'
        package-type: container
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"
        
